### ISSUE TITLE
Datasource deletion with no store deletion

### ISSUE THREAD

**Issue by rafa-guedes** [oceanum-io/oceanum-python#6]
When trying to delete a datasource with the `delete_datasource` method but the underlying store cannot be deleted (presumably because it is not in the expected location based on the id), a `DatameshConnectError` is raised (even though the actual datasource is actually deleted). Should we handle this exception and perhaps only throw a warning in those cases instead?

**Comment by ondave** [comment]
This is a datamesh system consistency error if this occurs, so I think we need to maintain this as an exception. Should not happen in normal operations.
