### ISSUE TITLE
Querying daily averaged SCHISM data.

### ISSUE THREAD

**Issue by simonweppe** [oceanum-io/oceanum-python#7]
Hi there @rafa-guedes @ondave ,
Following request is returning data averaged in time, but also space - am I doing something wrong ? (same query with ` "resolution": "native" ` works fine).
````
   oceanum_ocean_nz_schism_v1_query={"datasource":"oceanum_ocean_nz_schism_v1","parameters":{},
                                    "description":"Oceanum NZ ocean hindcast sigma layers",
                                    "variables":["SCHISM_hgrid_node_x","SCHISM_hgrid_node_y","depth","dahv","elev","wind_speed","wetdry_elem","wetdry_node","SCHISM_hgrid_face_nodes"],#,"hvel","zcor"],
                                    "geofilter":{"type":"bbox","geom":[173.0,-43.0,179.0,-41.0],"resolution":0.0},
                                    "timefilter":{"type":"range","times":time_str,
                                                    "resolution":'D',"resample":"mean"},"functions":[],
                                                    "id":"3ae5409cd477077ae5c87d0d012149cf"}
````

**Comment by rafa-guedes** [comment]
@simonweppe you aren't doing anything wrong, there is an issue on our side, we are working to fix it. Thanks for sending the reproducible example.

**Comment by ondave** [comment]
This was an issue the datamesh gateway, not the library itself. This has been fixed and should now work as expected.

**Comment by simonweppe** [comment]
Cheers - working fine now

**Comment by simonweppe** [comment]
Hi @rafa-guedes , @ondave ,

Not directly the same issue..but along the same lines so adding here.

We generally query variables one by one in our wrappers when downloading data, and then merge into a single file afterwards. It seems that the query with daily averaging fails when the queried variable has no time dimension (which can happen in our case when we query `SCHISM_hgrid_node_x` for example). It works fine if there is at least another variable that does have a time dimensions.

This fails : 
```
{'datasource': 'oceanum_ocean_nz_schism_v1', 'timefilter': {'type': 'range', 'times': [datetime.datetime(2020, 1, 1, 0, 0), datetime.datetime(2020, 1, 2, 0, 0)], 'resolution': 'D'}, 'geofilter': {'type': 'bbox', 'geom': [172.0, -43.0, 178.0, -39.0], 'resolution': 0.0}, 'variables': ['SCHISM_hgrid_node_x']}
```
This works fine:

```
{'datasource': 'oceanum_ocean_nz_schism_v1', 'timefilter': {'type': 'range', 'times': [datetime.datetime(2020, 1, 1, 0, 0), datetime.datetime(2020, 1, 2, 0, 0)], 'resolution': 'D'}, 'geofilter': {'type': 'bbox', 'geom': [172.0, -43.0, 178.0, -39.0], 'resolution': 0.0}, 'variables': ['SCHISM_hgrid_node_x', 'elev']}
```

Maybe it could return the original variable (not daily-averaged) rather than fail ?

**Comment by ondave** [comment]
This was a gateway bug that occurred if a a subset of variables without time were selected from a datasource with time - now fixed

**Comment by simonweppe** [comment]
Thanks - the above queries do work now, but I think there might still be something odd with the daily averaging, only if the specified bounds are beyond the SCHISM data extent (which I was setting to make sure I'd get the full extents East-West).

This works : 

`    query4 = {'datasource': 'oceanum_ocean_nz_schism_v1', 'timefilter': {'type': 'range', 'times': [datetime.datetime(2020, 1, 1, 0, 0), datetime.datetime(2020, 1, 2, 0, 0)], 'resolution': 'D'}, 'geofilter': {'type': 'bbox', 'geom': [172.0, -43.0, 178.0, -39.0], 'resolution': 0.0}, 'variables': ['elev']}`

But this fails :

`    query4 = {'datasource': 'oceanum_ocean_nz_schism_v1', 'timefilter': {'type': 'range', 'times': [datetime.datetime(2020, 1, 1, 0, 0), datetime.datetime(2020, 1, 2, 0, 0)], 'resolution': 'D'}, 'geofilter': {'type': 'bbox', 'geom': [168.0, -43.0, 178.0, -39.0], 'resolution': 0.0}, 'variables': ['elev']}`

If I use the native time resolution (with the same large extents), it works ok 

`    query4 = {'datasource': 'oceanum_ocean_nz_schism_v1', 'timefilter': {'type': 'range', 'times': [datetime.datetime(2020, 1, 1, 0, 0), datetime.datetime(2020, 1, 2, 0, 0)], 'resolution': 'native'}, 'geofilter': {'type': 'bbox', 'geom': [168.0, -43.0, 178.0, -39.0], 'resolution': 0.0}, 'variables': ['elev']}`

**Comment by simonweppe** [comment]
mmh I thought I could work around that by not setting a geofilter, but this fails too : 
`    query3 = {'datasource': 'oceanum_ocean_nz_schism_v1', 'timefilter': {'type': 'range', 'times': [datetime.datetime(2020, 1, 1, 0, 0), datetime.datetime(2020, 1, 2, 0, 0)], 'resolution': 'D'}, 'variables': ['elev']}
`
it works if I add a geofilter where bounds are within the SCHISM grid

**Comment by ondave** [comment]
Another gateway bug, fixed and redeployed
